services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: copilot
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: copilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
