services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8800:8000"   # Laravel
      - "5173:5173"   # Vite
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - ollama
    working_dir: /var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: copilot
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    command: >
      bash -c "composer install &&
               php artisan key:generate &&
               php artisan migrate &&
               npm install &&
               npm run dev & php artisan serve --host=0.0.0.0 --port=8000"

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: copilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  pgdata:
  ollama-data:
